- name: packages | install required packages (Linux)
  become: true
  package:
    name:
      - docker
      - docker-compose
      - lazygit
    state: latest
  when: ansible_system == "Linux"

# - name: packages | ensure docker service is enabled (Linux)
#   become: true
#   service:
#     name: 'docker.socket'
#     state: started
#     enabled: yes
#   when: ansible_system == "Linux"
#
# - name: packages | ensure docker service is enabled (Linux)
#   become: true
#   service:
#     name: docker
#     state: started
#     enabled: yes
#   when: ansible_system == "Linux"
#
# - name: packages | ensure containerd service is enabled (Linux)
#   become: true
#   service:
#     name: containerd
#     state: started
#     enabled: yes
#   when: ansible_system == "Linux"
#
# - name: packages | ensure systemd networkd wait online service is enabled (Linux)
#   become: true
#   service:
#     name: systemd-networkd-wait-online
#     state: stopped
#     enabled: no
#   when: ansible_distribution in ["Artix Linux", "Archlinux", "Debian"]

- name: "users | {{ user }} | ensure {{ user }} is in docker group (Linux)"
  become: true
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  when: ansible_system == "Linux"
