- name: users | "{{ user }}"
  become: true
  block:
    - name: users | "{{ user }}" | create group
      group:
        name: "{{ user }}"
        state: present

    - name: users | "{{ user }}" | create user
      user:
        name: "{{ user }}"
        group: "{{ user }}"
        groups: "{{ sudo_group }}"
        append: true
        state: present
        shell: /usr/bin/bash

    - name: users | "{{ user }}" | create .ssh directory
      file:
        path: "{{ item.dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0700
      with_items:
        - { dir: "/home/{{ user }}/.ssh" }

    - name: users | "{{ user }}" | copy key to host
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}"
