# Load distro specific variables
- include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_system == "Linux"

- block:
  - import_tasks: packages/install_packages.yml
  # - import_tasks: packages/install_qemu.yml
