- name: system setup | apt
  become: true
  block:
    - name: system setup | apt | disable recommended and suggested package installation (Debian)
      copy:
        src: system_setup/apt.conf
        dest: /etc/apt/apt.conf.d/99norec
        owner: root
        group: root

    - name: system setup | apt | Install unattended upgrades package.
      package:
        name: unattended-upgrades
        state: present

    - name: system setup | apt | Copy unattended-upgrades configuration files in place.
      template:
        src: "{{ item }}.j2"
        dest: "/etc/apt/apt.conf.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - 10periodic
        - 50unattended-upgrades
  when: ansible_os_family == "Debian"
