- name: system setup | fail2ban
  become: true
  block:
    - name: system setup | fail2ban | Install (Debian).
      package:
        name: fail2ban
        state: present
      when: ansible_os_family == 'Debian'

    # - name: system setup | fail2ban | Copy custom configuration file into place.
    #   template:
    #     src: "{{ security_fail2ban_custom_configuration_template }}"
    #     dest: /etc/fail2ban/jail.local
    #     owner: root
    #     group: root
    #     mode: 0644

    - name: system setup | fail2ban | Ensure service is running and enabled on boot.
      service:
        name: fail2ban
        state: started
        enabled: true
